<form class="form form-account-sms" name="" action="" method="post">
    <fieldset class="fieldset" data-container="general-configuration">
        <legend class="legend">
            <span data-title="general-configuration">
                <?php echo $block->escapeHtml(__('General Configuration')) ?>
            </span>
        </legend>
        <div class="field choice">
            <input type="checkbox" name="enable_notifications" id="enable-notifications" data-role="enable-notifications" value="1" title="<?= $block->escapeHtmlAttr(__('Enable SMS notifications')) ?>" class="checkbox" />
            <label class="label" for="change-email">
                <span>
                    <?php echo $block->escapeHtml(__('Enable SMS notifications')) ?>
                </span>
            </label>
        </div>
    </fieldset>
    <?php echo $block->getChildHtml("sms.section.orders"); ?>
    <fieldset class="fieldset " data-container="other-notifications">
        <legend class="legend">
            <span data-title="other-notifications">
                <?php echo $block->escapeHtml(__('Other Notifications')) ?>
            </span>
        </legend>
    </fieldset>
</form>