<form class="form form-account-sms" name="form-account-sms" action="" method="post">
    <fieldset class="fieldset" data-container="general-configuration">
        <legend class="legend">
            <span data-title="general-configuration">
                <?php echo $block->escapeHtml(__('General Configuration')) ?>
            </span>
        </legend>
        <div class="field choice">
            <input type="checkbox" name="enable_notifications" id="enable-notifications" data-role="enable-notifications" value="1" title="<?= $block->escapeHtmlAttr(__('Enable SMS notifications')) ?>" class="checkbox" />
            <label class="label" for="change-email">
                <span>
                    <?php echo $block->escapeHtml(__('Enable SMS notifications')) ?>
                </span>
            </label>
        </div>
    </fieldset>
    <?php echo $block->getChildHtml("sms.section.orders"); ?>
    <fieldset class="fieldset " data-container="other-notifications">
        <legend class="legend">
            <span data-title="other-notifications">
                <?php echo $block->escapeHtml(__('Other Notifications')) ?>
            </span>
        </legend>
    </fieldset>
</form>
<script>
    require([
        'jquery'
    ], function ($) {
        $(document).ready(function () {
            $("input[name='enable_notifications']").change (function (){
                var checked = $(this).prop("checked");
                $("form[name='form-account-sms'] input[type='checkbox']").prop("checked", checked);
            });
        });
    });
</script>