<div class="field choice sms">
    <input type="checkbox" name="sms_notifications" title="<?= $block->escapeHtmlAttr(__('Sign Up for SMS Notifications')) ?>" value="1" id="sms_notifications" class="checkbox">
    <label for="sms_notifications" class="label">
        <span><?php echo $block->escapeHtml(__('Sign Up for SMS Notifications')) ?></span>
        <span>
            (
            <a href="#" class="action"
               data-mage-init='{"tooltip": {"content": "<?php echo /* @noEscape */ '<p>' . $block->escapeHtml(__('Enabling SMS notifications means you agreed receiving SMS alerts to your specified order shipping address telephone.')) . '</p>'; ?>"}}'>
                <?php echo $block->escapeHtml(__('Terms and Conditions')) ?>
            </a>
            |
            <a href="#" class="action open-sms-modal" data-target="#sms-config-preferences">
                <?php echo $block->escapeHtml(__('Preferences')) ?>
            </a>
            )
        </span>
    </label>
</div>
<?php echo $block->getChildHtml(__("customer.sms.tooltip")); ?>