<?php
/**
 * LINK Mobility SMS Notifications
 *
 * Sends transactional SMS notifications through the LINK Mobility messaging
 * service.
 *
 * @author Joseph Leedy <joseph@wagento.com>
 * @author Yair García Torres <yair.garcia@wagento.com>
 * @copyright Copyright (c) Wagento (https://wagento.com/)
 * @license https://opensource.org/licenses/OSL-3.0.php Open Software License 3.0
 */

/** @var \Wagento\LinkMobilitySMSNotifications\Block\Customer\Account\Create\MobileTelephoneField $block */

/** @var \Wagento\LinkMobilitySMSNotifications\ViewModel\TelephonePrefixes $telephonePrefixesViewModel */
$telephonePrefixesViewModel = $block->getData('telephone_prefixes_view_model');
?>
<div class="field mobile-telephone-number" id="mobile-telephone-number-field" data-bind="scope: 'sms-mobile-telephone'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "#mobile-telephone-number-field": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "sms-mobile-telephone": {
                        "component": "Wagento_LinkMobilitySMSNotifications/js/view/mobile-telephone-field",
                        "config": {
                            "mobileTelephonePrefixOptions": <?= \json_encode($telephonePrefixesViewModel->getOptions()) ?>,
                            "defaultMobileTelephonePrefix": "<?= /** @noEscape */ $telephonePrefixesViewModel->getDefaultPrefix() ?>"
                        }
                    }
                }
            }
        }
    }
</script>