<?php
/**
 * Wagento SMS Notifications powered by LINK Mobility
 *
 * Sends transactional SMS notifications through the LINK Mobility messaging
 * service.
 *
 * @author Joseph Leedy <joseph@wagento.com>
 * @author Yair García Torres <yair.garcia@wagento.com>
 * @copyright Copyright (c) Wagento (https://wagento.com/)
 * @license https://opensource.org/licenses/OSL-3.0.php Open Software License 3.0
 */
?>
<?php /** @var \Wagento\SMSNotifications\Block\Customer\Account\Create\SubscribeField $block */ ?>
<div class="field choice sms-notification-subscription" id="sms-notification-subscription-field" data-bind="scope: 'sms-notification-subscription'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "#sms-notification-subscription-field": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "sms-notification-subscription": {
                        "component": "Wagento_SMSNotifications/js/view/sms-notification-subscription",
                        "isOptinRequired": <?= /* @noEscape */ $block->isOptinRequired() ? 'true' : 'false' ?>,
                        "isTermsAndConditionsShownAfterOptin": <?= /* @noEscape */ $block->isTermsAndConditionsShownAfterOptin() ? 'true' : 'false' ?>
                    }
                }
            }
        }
    }
</script>