<?php
/**
 * LINK Mobility SMS Notifications
 *
 * Sends transactional SMS notifications through the LINK Mobility messaging
 * service.
 *
 * @author Joseph Leedy <joseph@wagento.com>
 * @author Yair García Torres <yair.garcia@wagento.com>
 * @copyright Copyright (c) Wagento (https://wagento.com/)
 * @license https://opensource.org/licenses/OSL-3.0.php Open Software License 3.0
 */

/** @var Magento\Backend\Block\Template $block */
?>
<section id="sms-notifications-info" class="section-config">
    <header>
        <div class="logo-title-container">
            <a href="https://www.linkmobility.com/" target="_blank" class="logo"><img src="<?= $block->getViewFileUrl('Wagento_LinkMobilitySMSNotifications::images/lm-logo.svg') ?>" alt="LINK Mobility Group" width="300" height="46"></a>
            <h1><?= $block->escapeHtml(__('SMS Notifications')) ?></h1>
        </div>
        <p><small><?= $block->escapeHtml(__('Version %1', $block->getData('module_version'))) ?></small></p>
    </header>
    <nav>
        <ul>
            <li><a href="<?= $block->escapeUrl($block->getData('documentation_url')) ?>" target="_blank"><?= $block->escapeHtml(__('User Guide')) ?></a></li>
            <li><a href="<?= $block->escapeUrl($block->getData('overview_url')) ?>" target="_blank"><?= $block->escapeHtml(__('Plans and Pricing')) ?></a></li>
            <li><a href="<?= $block->escapeUrl($block->getData('signup_url')) ?>" target="_blank"><?= $block->escapeHtml(__('Sign Up For An Account')) ?></a></li>
        </ul>
    </nav>
    <main>
        <?= $block->escapeHtml($block->getData('info_text'), ['p', 'ul', 'li', 'a', 'strong', 'em']) ?>
        <p><a href="<?= $block->escapeUrl($block->getData('overview_url')) ?>" target="_blank"><?= $block->escapeHtml(__('Learn more about our SMS services')) ?></a></p>
    </main>
</section>
