<?php
/**
 * Wagento SMS Notifications powered by LINK Mobility
 *
 * Sends transactional SMS notifications through the LINK Mobility messaging
 * service.
 *
 * @author Joseph Leedy <joseph@wagento.com>
 * @author Yair García Torres <yair.garcia@wagento.com>
 * @copyright Copyright (c) Wagento (https://wagento.com/)
 * @license https://opensource.org/licenses/OSL-3.0.php Open Software License 3.0
 */

/** @var \Magento\Backend\Block\Template $block */
?>
<section id="sms-notifications-info" class="section-config">
    <header>
        <div class="logo-title-container">
            <a href="https://www.wagento.com/" target="_blank" class="wagento-logo"><img src="<?= $block->getViewFileUrl('Wagento_SMSNotifications::images/wagento-logo-dark.png') ?>" alt="Wagento" width="155" height="36"></a>
            <h1><?= $block->escapeHtml(__('SMS Notifications')) ?></h1>
            <p><span><?= $block->escapeHtml(__('powered by')) ?></span> <a href="https://www.linkmobility.com/" target="_blank" class="linkmobility-logo"><img src="<?= $block->getViewFileUrl('Wagento_SMSNotifications::images/linkmobility-logo.svg') ?>" alt="LINK Mobility Group" width="300" height="46"></a></p>
        </div>
        <p><small><?= $block->escapeHtml(__('Version %1', $block->getData('module_version'))) ?></small></p>
    </header>
    <nav>
        <ul>
            <li><a href="<?= $block->escapeUrl($block->getData('help_url')) ?>" target="_blank"><?= $block->escapeHtml(__('User Guide')) ?></a></li>
            <li><a href="<?= $block->escapeUrl($block->getData('more_url')) ?>" target="_blank"><?= $block->escapeHtml(__('Plans and Pricing')) ?></a></li>
        </ul>
    </nav>
    <main>
        <?= $block->escapeHtml($block->getData('info_text'), ['p', 'ul', 'li', 'a', 'strong', 'em']) ?>
    </main>
</section>
