<?php
/**
 * LINK Mobility SMS Notifications
 *
 * Sends transactional SMS notifications through the LINK Mobility messaging
 * service.
 *
 * @author Joseph Leedy <joseph@wagento.com>
 * @author Yair García Torres <yair.garcia@wagento.com>
 * @copyright Copyright (c) LINK Mobility (https://www.linkmobility.com/)
 * @license https://opensource.org/licenses/OSL-3.0.php Open Software License 3.0
 */
?>
<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div class="field-sms-notification-subscription" id="sms-notification-subscription-container" data-bind="scope: 'sms-notification-subscription'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "#sms-notification-subscription-container": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "sms-notification-subscription": {
                        "component": "Linkmobility_Notifications/js/view/sms-notification-subscription"
                    }
                }
            }
        }
    }
</script>